In [ ]:
price = [2, 1, 10]
type(price)


list

In [ ]:
quantity_sold = [17, 40, 1]
type(quantity_sold)


list

In [ ]:
import numpy as np


In [ ]:
#multiply arrays
price_array = np.array(price)
quantity_sold_array = np.array(quantity_sold)
type(price_array)

price_array*quantity_sold_array

array([34, 40, 10])

In [ ]:
cost_array = np.array([0.25, 0.50, 5.00])
#finding profit by multip diff arrays
profit_array = price_array - cost_array
print(profit_array)


[1.75 0.5  5.  ]


In [ ]:
profit_array > 2.00


array([False, False,  True])

In [ ]:
#adding item
price_array = np.append(price_array, 7)
print(price_array)

[ 2  1 10  7]


In [ ]:
#adding mulyiple items
price_array = np.append(price_array, [4.50, 3, 4, 9])
print(price_array)

#check data type
print(price_array.dtype)


[ 2.   1.  10.   7.   4.5  3.   4.   9.   4.5  3.   4.   9. ]
float64


In [ ]:
#deleting price
price_array = np.delete(price_array, -1)
print(price_array)


[ 2.   1.  10.   7.   4.5  3.   4.   9.   4.5  3.   4. ]


In [ ]:
#Changing price 
price_array[2] = 12
print(price_array)


[ 2.   1.  12.   7.   4.5  3.   4.   9.   4.5  3.   4. ]


In [ ]:
#2) Update the quantity_sold_array to include the sale of 2 pies, 3 trays of fudge, 16 cupcakes, and 5 loaves of banana bread. 

quantity_sold_array = np.append(quantity_sold_array, [2, 3, 16, 5])
print(quantity_sold_array)


[17 40  1  2  3 16  5]


In [ ]:
#2)You also realize that one of the cookies you thought was sold had actually fallen on the ground, 
#so edit the quantity_sold_array from 40 to 39.

quantity_sold_array[1] = 39
print(quantity_sold_array)

[17 39  1  2  3 16  5]


In [ ]:
#3) Determine the amount of money collected from the sale of each item at the bake sale.

money_collected=price_array*quantity_sold_array
print(money_collected)
sum(money_collected)

[34.  39.  12.  14.  13.5 48.  20. ]


180.5

In [ ]:
print(price_array)
print(cost_array)
print(quantity_sold_array)
print(quantity_leftover_array)

[ 2.   1.  12.   7.   4.5  3.   4. ]
[0.25 0.5  5.  ]
[17 39  1  2  3 16  5]
[0 0 2 1 6 0 2]


In [ ]:
#4) Create a NumPy array "quantity_leftover" that includes the quantity of each item remaining at the end of the sale: 
#2 cakes, 1 pie, 6 trays of fudge, 2 loaves of banana bread. Hint: Make sure to include "0" for any item that was sold out.
# Why is this important when creating the array?

quantity_leftover = [0,0,2,1,6,0,2]
quantity_leftover_array = np.array(quantity_leftover)
print(quantity_leftover_array)

#o's are important when creating array because they keep the index correct and aligned with each item


[0 0 2 1 6 0 2]


In [ ]:
#5)The club decides to sell the leftover items at half price and everything quickly sells out! 
#Determine how much money was collected from the clearance sale.

half_price= [0,0,6.0,3.5,2.25,0,2.0]
half_price_array= np.array(half_price)
print(half_price_array)
print(quantity_leftover_array)
sum(half_price_array*quantity_leftover_array)


[0.   0.   6.   3.5  2.25 0.   2.  ]
[0 0 2 1 6 0 2]


33.0

In [ ]:
#6) How much total money was collected from the bake sale (including the sale of full price and clearance items)?
#Hint: Your final answer should be $213.50, but you must make sure you get this answer with your NumPy coding skills!!

clearance_sold= sum(half_price_array*quantity_leftover_array)
full_price_sold= sum(money_collected)
money_collected= clearance_sold+full_price_sold
print(money_collected)

213.5
